import Head from 'next/head'
import Card from '../components/Card'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400;1,700&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div className="row">
            <Card image="obra-1.jpg" title="LA JOVEN DE LA PERLA" autor="Johannes Vermeer"></Card>
            <Card image="obra-2.jpg" title="LA MONA LISA" autor="Leonardo da Vinci"></Card>
            <Card image="obra-3.jpg" title="Terrazza del caffè la sera" autor="Vincent van Gogh"></Card>
            <Card image="obra-4.jpg" title="EL GRITO" autor="Edvard Munch"></Card>
            <Card image="obra-1.jpg" title="LA JOVEN DE LA PERLA" autor="Johannes Vermeer"></Card>
            <Card image="obra-2.jpg" title="LA MONA LISA" autor="Leonardo da Vinci"></Card>
            <Card image="obra-3.jpg" title="Terrazza del caffè la sera" autor="Vincent van Gogh"></Card>
            <Card image="obra-4.jpg" title="EL GRITO" autor="Edvard Munch"></Card>
          </div>
        </div>
      </main>

    </div>
  )
}
